name: "Prepare installers"
description: "Setups the NBPackage needed to build the installers"

runs:
  using: "composite"
  steps:
    - name: Prepare NBPackage
      run: bash prepare-installers.sh
      working-directory: installers
      shell: bash

    - name: Upload NBPackage
      uses: actions/upload-artifact@v7
      with:
       name: nbpackage
       path: installers/nbpackage/
       compression-level: 9