# This Action will build the SDK and if this succeeds, trigger a build on the
# jMonkeyEngine/sdk-update-center repository, so that NBMs get built and
# deployed
name: Nightly NBM Deployment

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  BuildSDK:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6

    - name: Build the SDK
      uses: ./.github/actions/build-sdk

  NBMDeployment:
    needs: [BuildSDK]
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
    - uses: actions/checkout@v6

    - name: Deploy NBMs
      uses: ./.github/actions/nbm-deployment
      with:
        token: ${{ secrets. UPDATE_CENTER_PAT }}