# This Action will build the SDK and if this succeeds, create a GitHub release
name: Release Builds
on:
  push:
    tags:
      - "*"
jobs:

  # -------------------------------
  # 1. Build + bundle (Linux only)
  # -------------------------------
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6

    - name: Build the SDK
      uses: ./.github/actions/build-sdk
      with:
        tag: ${{ github.ref_name }}
        createBundle: true

    - name: Prepare installers
      uses: ./.github/actions/prepare-installers

  # -------------------------------
  # 2. Native installer packaging (matrix)
  # -------------------------------
  package:
    needs: build

    strategy:
      matrix:
        os: [ ubuntu-latest, ubuntu-24.04-arm, windows-latest, macos-latest, macos-26-intel ]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v6

      - name: Build installers
        uses: ./.github/actions/build-installers
        with:
          tag: ${{ github.ref_name }}
          os: ${{ runner.os }}
          arch: ${{ runner.arch }}

  # -------------------------------
  # 3. Release
  # -------------------------------
  release:
    needs: package
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Publish release
        uses: ./.github/actions/publish-release
        with:
          tag: ${{ github.ref }}